version: "3.5"

services:
  atn-db:
    container_name: atn-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - ${DB_PORT}:5432
    volumes:
      - atn-db:/var/lib/postgresql/data

  atn-api:
    container_name: atn-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src

volumes:
  atn-db: